/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'doc',
      label: '一 简介',
      id: 'intro',
    },
    {
      type: 'category',
      label: '二 安装',
      items: [{
        type: 'autogenerated',
        dirName: 'documentation/installation'
      }]
    },
    {
      type: 'category',
      label: '三 快速入门',
      items: [{
        type: 'autogenerated',
        dirName: 'documentation/getStarted'
      }]
    },
    /*
    {
      type: 'category',
      label: '三 快速入门',
      items: [{
        type: 'category',
        label: '3.1 矢量数据导入',
        items: [{
          type: 'autogenerated',
          dirName: 'documentation/getStarted/import'
        }]
      },
      {
        type: 'category',
        label: '3.2 SQL建立空间数据表',
        items: [{
          type: 'autogenerated',
          dirName: 'documentation/getStarted/create'
        }]
      },
      {
        type: 'category',
        label: '3.3 空间查询',
        items: [{
          type: 'autogenerated',
          dirName: 'documentation/getStarted/query'
        }]
      }]
    }*/
  ],
  examples: [
    'examples/base'
  ]
};

module.exports = sidebars;
